baseURL = 'https://wineanddine.blog/'
languageCode = 'en-us'
title = 'Wine and Dine'
theme = 'hugo-theme-stack'

# Set hasCJKLanguage to true if your site includes Chinese/Japanese/Korean languages
hasCJKLanguage = false
copyright = "Wine and Dine"

# Pagination configuration (new syntax for Hugo v0.128.0+)
[pagination]
pagerSize = 5

# Theme i18n support
DefaultContentLanguage = "en"

# Change it to your Disqus shortname before using
disqusShortname = ""

[params]
mainSections = ["posts"]
featuredImageField = "image"
rssFullContent = true
favicon = "/favicon.png"

[params.footer]
since = 2025
customText = "A food & life blog"

[params.dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[params.sidebar]
emoji = "🍷"
subtitle = "From the Stovetop to the Grapevine"

[params.sidebar.avatar]
enabled = true
local = true
src = "img/avatar.png"

[params.article]
math = false
toc = true
readingTime = true

[params.article.license]
enabled = false

[params.comments]
enabled = false

[params.widgets]
homepage = []
page = []

[params.opengraph]
enabled = true

[params.opengraph.twitter]
site = ""
card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = false
local = false
src = ""

[params.colorScheme]
toggle = true
default = "auto"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

# Menu configuration
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[menu.main.params]
icon = "home"

# Social media links
[[menu.social]]
identifier = "x"
name = "X"
url = "https://x.com/wineanddineblg"
[menu.social.params]
icon = "brand-twitter"

# Markup configuration
[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4